# Generated by Django 5.0 on 2023-12-20 19:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto_Proteccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('descripcion', models.TextField()),
                ('cantidad', models.PositiveBigIntegerField()),
                ('imagen', models.ImageField(upload_to='')),
            ],
        ),
        migrations.RenameModel(
            old_name='Producto',
            new_name='Producto_almacen',
        ),
        migrations.CreateModel(
            name='Transaccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_persona', models.CharField(max_length=100)),
                ('cantidad_retirada', models.PositiveIntegerField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('producto_almacen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='datos.producto_almacen')),
                ('producto_proteccion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='datos.producto_proteccion')),
            ],
        ),
    ]
