# Generated by Django 5.0 on 2023-12-21 23:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datos', '0002_producto_proteccion_rename_producto_producto_almacen_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto_almacen',
            old_name='cantidad',
            new_name='cantidad_disponible',
        ),
        migrations.RenameField(
            model_name='producto_proteccion',
            old_name='cantidad',
            new_name='cantidad_disponible',
        ),
    ]
