# Generated by Django 5.0 on 2023-12-24 00:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datos', '0003_rename_cantidad_producto_almacen_cantidad_disponible_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RetiroProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_persona', models.CharField(max_length=255)),
                ('cantidad_retirada', models.PositiveIntegerField()),
                ('fecha_retiro', models.DateTimeField(auto_now_add=True)),
                ('producto_almacen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='datos.producto_almacen')),
                ('producto_proteccion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='datos.producto_proteccion')),
            ],
        ),
        migrations.DeleteModel(
            name='Transaccion',
        ),
    ]
