# Generated by Django 5.0 on 2023-12-24 04:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datos', '0006_alter_retiroproducto_producto_almacen_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto_almacen',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='producto_proteccion',
            name='descripcion',
        ),
        migrations.AlterField(
            model_name='retiroproducto',
            name='producto_almacen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='datos.producto_almacen'),
        ),
        migrations.AlterField(
            model_name='retiroproducto',
            name='producto_proteccion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='datos.producto_proteccion'),
        ),
    ]
